In [14]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import nltk
import json
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('wordnet')
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/kimwilmink/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/kimwilmink/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/kimwilmink/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kimwilmink/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
h2020_data = pd.read_csv("data/h2020_data.csv", index_col=0)
horizon_europe_data = pd.read_csv("data/horizon_europe_data.csv", index_col=0)
combined_data = pd.read_csv("data/combined_data.csv", index_col=0)

In [6]:
print(f"H2020 Data Shape: {h2020_data.shape}")
h2020_data.head(10)

H2020 Data Shape: (35447, 42)

,metadata_endDate,metadata_language,metadata_title,metadata_objective,metadata_callIdentifier,metadata_freeKeywords,metadata_DATASOURCE,metadata_REFERENCE,metadata_topicAbbreviation,metadata_overallBudget,...,databaseLabel,database,summary,weight,content,accessRestriction,enrichedMetadata,children,highlightedFragments,citation
metadata_es_SortDate,,,,,,,,,,,,,,,,,,,,,
2025-10-30T22:04:29.119+0100,2026-12-31T00:00:00.000+0100,en,A microbial perspective of major historical ev...,Microbes have played fundamental roles through...,ERC-2020-STG,"['The Americas', 'Ancient DNA', 'Native Americ...",SEDIA_NONH2020_PROD,31045243948800,ERC-2020-STG,1500000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,A microbial perspective of major historical ev...,0.0,A microbial perspective of major historical ev...,False,NaN,NaN,NaN,A microbial perspective of major historical ev...
2025-10-30T02:03:33.117+0100,2025-02-28T00:00:00.000+0100,en,Embedded Electronic solutions for Polymer Inno...,El-Peacetolero’s overarching ambition is to de...,NFRP-2019-2020,"['Embedded optoelectronic system', 'Diagnosis ...",SEDIA_NONH2020_PROD,31045243945320,NFRP-2019-2020-04,3652170.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Embedded Electronic solutions for Polymer Inno...,0.0,Embedded Electronic solutions for Polymer Inno...,False,NaN,NaN,NaN,Embedded Electronic solutions for Polymer Inno...
2025-10-29T21:56:18.755+0100,2025-12-31T00:00:00.000+0100,en,"Accurate, Reliable and Optimized functional MA...",The AROMA project will provide the means enabl...,H2020-FETOPEN-2018-2020,"['Ultra-high field', 'methods', 'RF pulse desi...",SEDIA_NONH2020_PROD,31045243885876,FETOPEN-01-2018-2019-2020,3601526.25,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,"Accurate, Reliable and Optimized functional MA...",0.0,"Accurate, Reliable and Optimized functional MA...",False,NaN,NaN,NaN,"Accurate, Reliable and Optimized functional MA..."
2025-10-29T02:27:11.382+0100,2027-06-30T00:00:00.000+0100,en,Tracing language and population mixing in the ...,Chinese history was co-constructed by Han (Chi...,ERC-2019-ADG,"['populations', 'anthropolgoy', 'language cont...",SEDIA_NONH2020_PROD,31045243883700,ERC-2019-ADG,2497850.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Tracing language and population mixing in the ...,0.0,Tracing language and population mixing in the ...,False,NaN,NaN,NaN,Tracing language and population mixing in the ...
2025-10-29T02:27:10.392+0100,2026-06-30T00:00:00.000+0100,en,Early Arabic Printing for the Arab Christians....,The main objective of the Project is to examin...,ERC-2019-ADG,"['Printing', 'Arab Christians', 'Arabic langua...",SEDIA_NONH2020_PROD,31045243883219,ERC-2019-ADG,2500000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Early Arabic Printing for the Arab Christians....,0.0,Early Arabic Printing for the Arab Christians....,False,NaN,NaN,NaN,Early Arabic Printing for the Arab Christians....
2025-10-29T02:27:06.718+0100,2024-06-30T00:00:00.000+0100,en,Integrated Urban Electric Mobility Solutions i...,The project SOLUTIONSplus aims to set up a glo...,H2020-LC-GV-2018-2019-2020,"['Innovation', 'demonstration', 'e-mobility', ...",SEDIA_NONH2020_PROD,31045243875041,LC-GV-05-2019,20094343.72,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Integrated Urban Electric Mobility Solutions i...,0.0,Integrated Urban Electric Mobility Solutions i...,False,NaN,NaN,NaN,Integrated Urban Electric Mobility Solutions i...
2025-10-28T23:11:01.954+0100,2025-06-30T00:00:00.000+0100,en,Dynamic longitudinal exposome trajectories in ...,"Environmental factors, including air and noise...",H2020-SC1-BHC-2018-2020,"['Life-course', 'Cardiometabolic health trajec...",SEDIA_NONH2020_PROD,31045243874739,SC1-BHC-28-2019,11997448.75,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Dynamic longitudinal exposome trajectories in ...,0.0,Dynamic longitudinal exposome trajectories in ...,False,NaN,NaN,NaN,Dynamic longitudinal exposome trajectories in ...
2025-10-28T03:03:15.150+0100,2024-12-31T00:00:00.000+0100,en,International Network for Terrestrial Research...,Planet Earth faces unprecedented environmental...,H2020-INFRAIA-2018-2020,"['Integrated', 'advanced pan-arctic infrastruc...",SEDIA_NONH2020_PROD,31045243871120,INFRAIA-01-2018-2019,10000000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,International Network for Terrestrial Research...,0.0,International Network for Terrestrial Research...,False,NaN,NaN,NaN,International Network for Terrestrial Research...
2025-10-28T03:03:01.311+0100,2024-11-30T00:00:00.000+0100,en,The Integrated Initiative of European Laser Re...,LASERLAB-EUROPE is the European consortium of ...,H2020-INFRAIA-2018-2020,"['Lasers', 'Physical Sciences', 'Optical Techn...",SEDIA_NONH2020_PROD,31045243871124,INFRAIA-01-2018-2019,10000000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,The Integrated Initiative of European Laser Re...,0.0,The Integrated Initiative of European Laser Re...,False,NaN,NaN,NaN,The Integrated Initiative of European Laser Re...
2025-10-28T03:02:59.812+0100,2025-04-30T00:00:00.000+0100,en,European network for developing new horizons f...,This EURIZON project proposal is about Europea...,H2020-INFRASUPP-2018-2020,"['Research Infrastructures', ' European-Russia...",SEDIA_NONH2020_PROD,31045243871072,INFRASUPP-01-2018-2019,24767360.43,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,European network for developing new horizons f...,0.0,European network for developing new horizons f...,False,NaN,NaN,NaN,European network for developing new horizons f...

In [7]:
print(f"Horizon Europe Data Shape: {horizon_europe_data.shape}")
horizon_europe_data.head(10)

Horizon Europe Data Shape: (23332, 42)

,metadata_endDate,metadata_language,metadata_title,metadata_objective,metadata_callIdentifier,metadata_freeKeywords,metadata_DATASOURCE,metadata_REFERENCE,metadata_topicAbbreviation,metadata_overallBudget,...,databaseLabel,database,summary,weight,content,accessRestriction,enrichedMetadata,children,highlightedFragments,citation
metadata_es_SortDate,,,,,,,,,,,,,,,,,,,,,
2025-12-17T23:23:16.707+0100,2027-05-31T00:00:00.000+0100,en,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...,SUNBIO brings together a significant variety o...,HORIZON-MISS-2023-OCEAN-01,"['wave energy', 'solar energy', 'thermal energ...",SEDIA_NONH2020_PROD,43108390101157493,HORIZON-MISS-2023-OCEAN-01-06,1869000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...,0.0,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...,False,NaN,NaN,NaN,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...
2025-12-16T14:48:37.868+0100,2028-12-31T00:00:00.000+0100,en,Three Dimensional Quantum Nanomaterials,Quantum nanomaterials are highly relevant for ...,ERC-2023-STG,NaN,SEDIA_NONH2020_PROD,43108390101116043,ERC-2023-STG,1500000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Three Dimensional Quantum Nanomaterials,0.0,Three Dimensional Quantum Nanomaterials,False,NaN,NaN,NaN,Three Dimensional Quantum Nanomaterials. Avail...
2025-12-16T14:12:26.033+0100,2028-09-30T00:00:00.000+0100,en,How to evolve without centromeres: meiotic rec...,Centromeres strongly affect genomic architectu...,ERC-2023-STG,"['centromere', 'holocentric chromosome', 'chro...",SEDIA_NONH2020_PROD,43108390101114879,ERC-2023-STG,1499980.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,How to evolve without centromeres: meiotic rec...,0.0,How to evolve without centromeres: meiotic rec...,False,NaN,NaN,NaN,How to evolve without centromeres: meiotic rec...
2025-12-15T17:27:52.798+0100,2026-07-31T00:00:00.000+0100,en,Geography and Cartography in Dante's «Comedy»,\nThe GEODETIC project aims to explore an unde...,HORIZON-MSCA-2022-PF-01,"['Dante Studies', 'Medieval and Italian Studie...",SEDIA_NONH2020_PROD,43108390101110048,HORIZON-MSCA-2022-PF-01-01,288859.20,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Geography and Cartography in Dante's «Comedy»,0.0,Geography and Cartography in Dante's «Comedy»,False,NaN,NaN,NaN,Geography and Cartography in Dante's «Comedy»....
2025-12-15T17:19:18.372+0100,2025-09-30T00:00:00.000+0100,en,Investigating if recuperating hepatic macropha...,Liver fibrosis is the build-up of scar tissue ...,HORIZON-MSCA-2022-PF-01,Macrophages; Fibrosis; Cirrhosis; Infection; M...,SEDIA_NONH2020_PROD,43108390101109513,HORIZON-MSCA-2022-PF-01-01,175920.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Investigating if recuperating hepatic macropha...,0.0,Investigating if recuperating hepatic macropha...,False,NaN,NaN,NaN,Investigating if recuperating hepatic macropha...
2025-12-15T05:22:58.915+0100,2025-12-31T00:00:00.000+0100,en,Automated zero-touch cross-layer provisioning ...,NaN,HORIZON-JU-SNS-2022,"['5G', '6G', 'service orchestration', 'zero-to...",SEDIA_NONH2020_PROD,43108390101097122,HORIZON-JU-SNS-2022-STREAM-A-01-07,6306388.31,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Automated zero-touch cross-layer provisioning ...,0.0,Automated zero-touch cross-layer provisioning ...,False,NaN,NaN,NaN,Automated zero-touch cross-layer provisioning ...
2025-12-15T05:22:50.224+0100,2026-12-31T00:00:00.000+0100,en,A European “shield” against colorectal cancer ...,With Colorectal Cancer (CRC) being accountable...,HORIZON-MISS-2021-CANCER-02,"['Colorectal cancer screening', 'early detecti...",SEDIA_NONH2020_PROD,43108390101097036,HORIZON-MISS-2021-CANCER-02-01,12972076.25,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,A European “shield” against colorectal cancer ...,0.0,A European “shield” against colorectal cancer ...,False,NaN,NaN,NaN,A European “shield” against colorectal cancer ...
2025-12-15T01:00:34.786+0100,2027-01-31T00:00:00.000+0100,en,Modular AXIal flux Motor for Automotive,The massive electrification of automotive vehi...,HORIZON-CL5-2022-D5-01,"['electrical machine', 'mass production', 'man...",SEDIA_NONH2020_PROD,43108390101096097,HORIZON-CL5-2022-D5-01-09,5684903.71,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Modular AXIal flux Motor for Automotive,0.0,Modular AXIal flux Motor for Automotive,False,NaN,NaN,NaN,Modular AXIal flux Motor for Automotive. Avail...
2025-12-14T23:34:25.721+0100,2026-12-31T00:00:00.000+0100,en,Systemic Endotoxemia as the driver of chronic ...,Rheumatic diseases (RDs) affect more than 40% ...,HORIZON-HLTH-2022-STAYHLTH-02,"['chronic inflammation', 'Microbiota', 'system...",SEDIA_NONH2020_PROD,43108390101095084,HORIZON-HLTH-2022-STAYHLTH-02-01,6997820.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Systemic Endotoxemia as the driver of chronic ...,0.0,Systemic Endotoxemia as the driver of chronic ...,False,NaN,NaN,NaN,Systemic Endotoxemia as the driver of chronic ...
2025-12-14T22:07:27.753+0100,2028-12-31T00:00:00.000+0100,en,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,Chronic inflammation underlies several disease...,HORIZON-HLTH-2022-STAYHLTH-02,Glycosylation; Microbiome; Innate Immune Respo...,SEDIA_NONH2020_PROD,43108390101093997,HORIZON-HLTH-2022-STAYHLTH-02-01,6771571.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,0.0,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,False,NaN,NaN,NaN,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...

In [8]:
print(f"Combined Data Shape: {combined_data.shape}")
combined_data.head(10)

Combined Data Shape: (58780, 42)

,metadata_endDate,metadata_language,metadata_title,metadata_objective,metadata_callIdentifier,metadata_freeKeywords,metadata_DATASOURCE,metadata_REFERENCE,metadata_topicAbbreviation,metadata_overallBudget,...,databaseLabel,database,summary,weight,content,accessRestriction,enrichedMetadata,children,highlightedFragments,citation
metadata_es_SortDate,,,,,,,,,,,,,,,,,,,,,
2025-10-31T03:41:37.475+0100,2024-08-31T00:00:00.000+0100,en,Sustainable 5G deployment model for future mob...,5GMed brings together key stakeholders of the ...,H2020-ICT-2018-20,"['5G-enabled mobility', 'cross-border corridor...",SEDIA_NONH2020_PROD,31045243951947,ICT-53-2020,15507441.35,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Sustainable 5G deployment model for future mob...,0.0,Sustainable 5G deployment model for future mob...,False,NaN,NaN,NaN,Sustainable 5G deployment model for future mob...
2025-10-30T22:04:29.119+0100,2026-12-31T00:00:00.000+0100,en,A microbial perspective of major historical ev...,Microbes have played fundamental roles through...,ERC-2020-STG,"['The Americas', 'Ancient DNA', 'Native Americ...",SEDIA_NONH2020_PROD,31045243948800,ERC-2020-STG,1500000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,A microbial perspective of major historical ev...,0.0,A microbial perspective of major historical ev...,False,NaN,NaN,NaN,A microbial perspective of major historical ev...
2025-10-30T02:03:33.117+0100,2025-02-28T00:00:00.000+0100,en,Embedded Electronic solutions for Polymer Inno...,El-Peacetolero’s overarching ambition is to de...,NFRP-2019-2020,"['Embedded optoelectronic system', 'Diagnosis ...",SEDIA_NONH2020_PROD,31045243945320,NFRP-2019-2020-04,3652170.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Embedded Electronic solutions for Polymer Inno...,0.0,Embedded Electronic solutions for Polymer Inno...,False,NaN,NaN,NaN,Embedded Electronic solutions for Polymer Inno...
2025-10-29T21:56:18.755+0100,2025-12-31T00:00:00.000+0100,en,"Accurate, Reliable and Optimized functional MA...",The AROMA project will provide the means enabl...,H2020-FETOPEN-2018-2020,"['Ultra-high field', 'methods', 'RF pulse desi...",SEDIA_NONH2020_PROD,31045243885876,FETOPEN-01-2018-2019-2020,3601526.25,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,"Accurate, Reliable and Optimized functional MA...",0.0,"Accurate, Reliable and Optimized functional MA...",False,NaN,NaN,NaN,"Accurate, Reliable and Optimized functional MA..."
2025-10-29T02:27:11.382+0100,2027-06-30T00:00:00.000+0100,en,Tracing language and population mixing in the ...,Chinese history was co-constructed by Han (Chi...,ERC-2019-ADG,"['populations', 'anthropolgoy', 'language cont...",SEDIA_NONH2020_PROD,31045243883700,ERC-2019-ADG,2497850.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Tracing language and population mixing in the ...,0.0,Tracing language and population mixing in the ...,False,NaN,NaN,NaN,Tracing language and population mixing in the ...
2025-10-29T02:27:10.392+0100,2026-06-30T00:00:00.000+0100,en,Early Arabic Printing for the Arab Christians....,The main objective of the Project is to examin...,ERC-2019-ADG,"['Printing', 'Arab Christians', 'Arabic langua...",SEDIA_NONH2020_PROD,31045243883219,ERC-2019-ADG,2500000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Early Arabic Printing for the Arab Christians....,0.0,Early Arabic Printing for the Arab Christians....,False,NaN,NaN,NaN,Early Arabic Printing for the Arab Christians....
2025-10-29T02:27:06.718+0100,2024-06-30T00:00:00.000+0100,en,Integrated Urban Electric Mobility Solutions i...,The project SOLUTIONSplus aims to set up a glo...,H2020-LC-GV-2018-2019-2020,"['Innovation', 'demonstration', 'e-mobility', ...",SEDIA_NONH2020_PROD,31045243875041,LC-GV-05-2019,20094343.72,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Integrated Urban Electric Mobility Solutions i...,0.0,Integrated Urban Electric Mobility Solutions i...,False,NaN,NaN,NaN,Integrated Urban Electric Mobility Solutions i...
2025-10-28T23:11:01.954+0100,2025-06-30T00:00:00.000+0100,en,Dynamic longitudinal exposome trajectories in ...,"Environmental factors, including air and noise...",H2020-SC1-BHC-2018-2020,"['Life-course', 'Cardiometabolic health trajec...",SEDIA_NONH2020_PROD,31045243874739,SC1-BHC-28-2019,11997448.75,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Dynamic longitudinal exposome trajectories in ...,0.0,Dynamic longitudinal exposome trajectories in ...,False,NaN,NaN,NaN,Dynamic longitudinal exposome trajectories in ...
2025-10-28T03:03:15.150+0100,2024-12-31T00:00:00.000+0100,en,International Network for Terrestrial Research...,Planet Earth faces unprecedented environmental...,H2020-INFRAIA-2018-2020,"['Integrated', 'advanced pan-arctic infrastruc...",SEDIA_NONH2020_PROD,31045243871120,INFRAIA-01-2018-2019,10000000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,International Network for Terrestrial Research...,0.0,International Network for Terrestrial Research...,False,NaN,NaN,NaN,International Network for Terrestrial Research...
2025-10-28T03:03:01.311+0100,2024-11-30T00:00:00.000+0100,en,The Integrated Initiative of European Laser Re...,LASERLAB-EUROPE is the European consortium of ...,H2020-INFRAIA-2018-2020,"['Lasers', 'Physical Sciences', 'Optical Techn...",SEDIA_NONH2020_PROD,31045243871124,INFRAIA-01-2018-2019,10000000.00,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,The Integrated Initiative of European Laser Re...,0.0,The Integrated Initiative of European Laser Re...,False,NaN,NaN,NaN,The Integrated Initiative of European Laser Re...

In [10]:
stop_words = set(stopwords.words("english"))

# adding additional words
stop_words.update(["project", "goal", "research", "new"])

In [11]:

def flatten(val):
    if isinstance(val, list):
        return " ".join(str(v) for v in val)
    return str(val) if pd.notna(val) else ""

In [ ]:
# Specify relevant columns
RELEVANT_COLUMNS = ["metadata_title", "metadata_objective", "metadata_freeKeywords"]

# Combine the text columns into a single string per row. Remove list objects and turn them into strings, and replace new lines with spaces.
combined_data["_combined_text"] = combined_data[RELEVANT_COLUMNS].map(flatten).agg(" ".join, axis=1).str.replace('\n', ' ')

corpus = combined_data["_combined_text"].tolist()

# TODO: add a column with the startdate of the project to the corpus

In [13]:
corpus[:5]  # Display the first 5 combined text entries

["Sustainable 5G deployment model for future mobility in the Mediterranean Cross-Border Corridor 5GMed brings together key stakeholders of the “Barcelona – Perpignan” cross-border section of the Mediterranean corridor including MNOs, road and rail operators and neutral hosts, complemented with innovative SMEs developing AI functions, and selected R&D centers with a proven track record in 5G research and innovation. Given the proximity of the E15 highway and the high-speed rail track in the considered cross-border section, the 5GMed consortium will demonstrate how a multi-stakeholder 5G infrastructure featuring a variety of technologies, including Rel.16 5GNR at 3.5 GHz, Rel.16 NR-V2X at 5.9 GHz, unlicensed mm-wave, network slicing and service orchestration, can be used to jointly deliver CCAM and FRMCS services. The considered CCAM use cases include Remote Driving in cross-border open roads to enable safe fallback operation in Level 4 autonomous driving, and the massive sensorization of road infrastructures enabling AI-powered traffic management algorithms in the presence of legacy vehicles. The considered FRMCS use cases include performance services where AI-functions running on the infrastructure side analyze camera feeds from high speed trains in real-time, and business services providing high-speed internet to passengers and in-train neutral hosting capabilities to MNOs. A Follow Me Infotainment use case will demonstrate live migration of media functions across cross-border scenarios both in automotive and railways environments.  The technical activities of 5GMed are complemented by a carefully designed impact maximization strategy including: i) demonstrations in key industrial events, ii) concrete measures to influence standardization and policy makers, iii) cost-benefit analysis of the 5GMed deployment models, and iv) joint exploitation and business modes.  5GMed ambitions to become the lighthouse project for CCAM and FRMCS deployment in cross-border scenarios that can be replicated across Europe and trigger further investments through the CEF2 program. ['5G-enabled mobility', 'cross-border corridor', 'cooperative', 'connected and automated transport', 'smart mobility and services', 'Infrastructure', 'sustainable 5G deployment']",
 "A microbial perspective of major historical events in the Southern Cone of the Americas Microbes have played fundamental roles throughout our evolution and history. These roles were not only played by pathogens, but also by the trillions of microorganisms inhabiting our body –the microbiome–, which are essential for homeostasis, physiology, and health. Recent advances in ancient DNA research have made possible to study infectious diseases and human microbiomes from ancient human populations, but this field of research is still at its early stages. For instance, it remains largely unknown which were the microbes (including pathogens) that associated with humans in the past, how they have changed over time, geographic regions and historical events, and to which extent these changes shaped our history and fate. This project will combine state-of-the-art methodologies from phylogenomics, microbiome research, and ancient DNA to bring a new perspective to the study of the human past. This approach will be implemented to investigate major aspects of the history of the Americas, using the Southern Cone as a study-model. First, the microbes (including pathogens) and microbiomes associated with pre-contact Native American populations will be characterized. This reference dataset will be then used to evaluate the impact of the agricultural transition and the European colonization in the oral microbiomes and infectious diseases of these populations. Finally, ancient pathogen genomics will be used to reconstruct the epidemiological scenarios of well-documented post-colonial epidemics. From a technical point of view, this project will also contribute new methods and applications to the emerging field of paleometagenomics. Overall, this work will bring unprecedented evidence to long-lasting debates regarding the impact of the agricultural transition in health and the intercontinental exchange of microbes during the European colonization, add a temporal perspective to the study of human microbiomes and infectious diseases and provide a new framework to study our past. ['The Americas', 'Ancient DNA', 'Native American populations', 'Microbial genomics', 'Phylogenomics', 'Infectious Diseases', 'Pathogen emergence and spread', 'Oral Microbiome', 'Agricultural Transition', 'European Colonization', 'Epidemics']",
 "Embedded Electronic solutions for Polymer Innovative Scanning Tools using Light Emitting devices for diagnostic Routines El-Peacetolero’s overarching ambition is to design a TRL 7 hand-held, low power, embedded optoelectronic system that can deploy AI for in-situ real-time measurement, identification and diagnosis of the material state of aging polymers in an industrial environment.  This optoelectronic system will be compact, ergonomic, modular, low power consumption, low cost and can be used by a technician or installed on a robot to perform non-invasive monitoring and analysis of polymers used in industrial environments for protection and insulation. To develop prototype, we will create a database of aged polymer samples and  their ATR-FTIR measurements. Moreover, El-Peacetolero will develop artificial intelligence based algorithms for polymer identification, diagnosis, and early detection of the aging condition.To construct the system, El-Peacetolero will develop a compact, high brightness, multi-wavelengths, measuring head including IR sources(LED/Laser), ATR crystal and detectors in the same package. El Peacetolero’s accuracy will be evaluated through focusing on reference characterisation of aged polymer samples to throughout its design phases. The impact of its operating conditions (radiative environments) on its electronic components will also be thoroughly studied . At the end of the project, El-Peacetolero will be used for performing measurements inside pipes on an equipped robot, which can operate inside the pipes. The El-Peacetolero has the potential for a huge impact. Already within the nuclear industry it will save time and money by implementing easy non-destructive techniques for the identification and diagnosis of polymers. It will also have an impact on the security and safety of the industry as aging polymers on cables and pipes can cause massive safety issues. These safety issues can also be transferred to other industries such as cabling on airplanes, where a technology such as El-Peacetolero could provide invaluable assistance in identifying potential problems. ['Embedded optoelectronic system', 'Diagnosis of polymer aging', 'Safety of reactors', 'early detection', 'data science', 'Artificial Intelligence', 'innovation in the safety of reactors', 'decommissioning']",
 "Accurate, Reliable and Optimized functional MAgnetic resonance imaging at unprecedented field strength for unique exploration of the human brain The AROMA project will provide the means enabling in vivo non-invasive exploration of cognitive functions of the human brain at the mesoscopic scale (500 μm). This will be achieved with non-incremental Magnetic Resonance Imaging (MRI) technologies at unprecedented field strength (11.7 Tesla). The following ambitious objectives are considered: -Maximize signal by means of advanced sequence developments, innovative coil designs, motion correction and paradigm shift radiofrequency pulse designs. -Exploit the emerging field sensors technology to minimize the noise induced by subject’s motion and physiology to achieve the functional targeted detection sensitivity. -Test and validate the disruptive scientific progress with tens of healthy adult volunteers for validation of the anatomical scan quality as well as reliable detection of cortical-depth dependent neural activations. AROMA is a multidisciplinary project engaging 6 EU partners (with young researchers and first-time participants to FET) from 5 countries (France, Germany, Switzerland, Netherlands and United Kingdom) covering the academic and industrial worlds. An implementation plan is presented in the form of 5 work packages, 4 of which are technical in nature. Synergy in communication and dissemination by the several partners and stakeholders (external advisory board, letters of intent are provided) will permit to maximize AROMA project impact. The proposal presents solutions to overcome the fundamental barriers and considers appropriate deliverables, tasks, milestones and risks in order to complete the project objectives in due time. Medical sector will be impacted by the AROMA project outcomes, with implications for computational psychiatry and deciphering the encoding of words, mathematical objects and conscious thoughts. The arsenal of techniques deployed in the project will constitute paradigm shifts with a unified solution, and with commercial opportunities and benefits for the MRI industry in general. ['Ultra-high field', 'methods', 'RF pulse design', 'RF coils', 'field sensors', 'motion correction', 'sequence programming', 'brain exploration', 'neuroscience']",
 "Tracing language and population mixing in the Gansu-Qinghai area Chinese history was co-constructed by Han (Chinese) people, transmitters of farming language and culture, and non-Han people, typically transmitters of nomadic language and culture in North and Northwest China. Governance by non-Han steppe rulers lasted for almost ten centuries (half of the history of imperial China since the First Emperor of Qin) and the Gansu-Qinghai area was the most important migration corridor between Central and East Asia. These languages and populations have competed, mixed and merged for ages. Surprisingly, a cross-linguistically comprehensive portrait of this region is missing in spite of individual language descriptions.  The present Project will study language mixture and language replacement patterns in the Gansu-Qinghai area, which geographically constitutes a natural demarcation between nomadic herders and farmers. In this intense contact area, home to nomadic languages and populations, Sinitic (Han) languages started to resemble non-Han languages, adopting similar syntactic means, while Yugur languages (Western Yugur belongs to Turkic language group and Eastern Yugur belongs to Mongolic language group), spoken by typical nomadic populations, kept their syntax relatively intact. The mixing degree of languages and populations in this area remains unclear, and in-depth research with an interdisciplinary approach is necessary.   The Project will determine the linguistic situation in this anthropological corridor by targeting two nomadic languages (Western and Eastern Yugur) and a variety of Sinitic languages. The analysis of language mixing and language replacement processes will be based on quantified data modeling, part of which will come from molecular anthropology and other fields such as history and archeology. This interdisciplinary approach will offer a global vision of language and population mixing in the Gansu-Qinghai area and a living sample of language preservation or loss due to different lifestyles and cultures.  ['populations', 'anthropolgoy', 'language contact']"]

In [16]:
with open("data/corpus.json", "w", encoding="utf-8") as file:
    json.dump(corpus, file, ensure_ascii=False)