In [33]:
import sedia_api_fetchers
import pandas as pd
from sedia_api_fetchers.EUFT_retrieve_projects import SEDIA_GET_PROJECTS

In [2]:
fetcher = SEDIA_GET_PROJECTS(
    flatten_metadata=True,      # Flatten nested JSON structures
    enrich_with_details=False   # Fetch detailed info (projects only)
)

In [3]:
h2020_data = fetcher.get('h2020', save=True)

Starting comprehensive fetch and processing for programme IDs: [31045243]...
🔍 DEBUG: Programme IDs being processed: [31045243]
🔍 DEBUG: Number of programmes: 1
Starting fetch for programme IDs: [31045243]...
Starting fetch with partitioning support...
Found 35,448 total records
Dataset exceeds 10,000 limit. Using date range partitioning...
Date range: 2025-01-24T14:32:52.086+0100 to 2026-08-06T04:23:05.770+0200

Overall Progress:   0%|          | 0/35448 [00:00<?, ?rec/s]

Splitting large chunk: 35,447 records (2025-01-24 to 2026-08-06)
Fetching chunk: 422 records (2025-01-24 to 2025-10-30)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

Overall Progress:   1%|          | 422/35448 [00:04<06:52, 84.99rec/s]

[DEBUG] Page 5 → 22 hits
Splitting large chunk: 35,025 records (2025-10-30 to 2026-08-06)
Fetching chunk: 48 records (2025-10-30 to 2026-03-19)

Overall Progress:   1%|▏         | 470/35448 [00:07<09:48, 59.42rec/s]

[DEBUG] Page 1 → 48 hits
Splitting large chunk: 34,977 records (2026-03-19 to 2026-08-06)
Splitting large chunk: 16,701 records (2026-03-19 to 2026-05-28)
Splitting large chunk: 18,276 records (2026-05-28 to 2026-08-06)
Fetching chunk: 702 records (2026-03-19 to 2026-04-23)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

Overall Progress:   3%|▎         | 1172/35448 [00:15<07:44, 73.85rec/s]

[DEBUG] Page 8 → 2 hits
Splitting large chunk: 15,999 records (2026-04-23 to 2026-05-28)
Splitting large chunk: 17,010 records (2026-05-28 to 2026-07-02)
Fetching chunk: 1,266 records (2026-07-02 to 2026-08-06)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

Overall Progress:   7%|▋         | 2438/35448 [00:28<06:01, 91.33rec/s]

[DEBUG] Page 13 → 66 hits
Fetching chunk: 2,228 records (2026-04-23 to 2026-05-10)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

Overall Progress:   7%|▋         | 2438/35448 [00:39<06:01, 91.33rec/s]

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

Overall Progress:  13%|█▎        | 4666/35448 [00:44<04:27, 114.86rec/s]

[DEBUG] Page 23 → 28 hits
Splitting large chunk: 13,771 records (2026-05-10 to 2026-05-28)
Splitting large chunk: 11,601 records (2026-05-28 to 2026-06-14)
Fetching chunk: 5,409 records (2026-06-14 to 2026-07-02)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

Overall Progress:  13%|█▎        | 4666/35448 [00:59<04:27, 114.86rec/s]

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

Overall Progress:  28%|██▊       | 10075/35448 [01:24<03:18, 127.90rec/s]

[DEBUG] Page 55 → 9 hits
Fetching chunk: 8,871 records (2026-05-10 to 2026-05-19)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

Overall Progress:  28%|██▊       | 10075/35448 [01:39<03:18, 127.90rec/s]

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

[DEBUG] Page 55 → 100 hits

[DEBUG] Page 56 → 100 hits

[DEBUG] Page 57 → 100 hits

[DEBUG] Page 58 → 100 hits

[DEBUG] Page 59 → 100 hits

[DEBUG] Page 60 → 100 hits

[DEBUG] Page 61 → 100 hits

[DEBUG] Page 62 → 100 hits

[DEBUG] Page 63 → 100 hits

[DEBUG] Page 64 → 100 hits

[DEBUG] Page 65 → 100 hits

[DEBUG] Page 66 → 100 hits

[DEBUG] Page 67 → 100 hits

[DEBUG] Page 68 → 100 hits

[DEBUG] Page 69 → 100 hits

[DEBUG] Page 70 → 100 hits

[DEBUG] Page 71 → 100 hits

[DEBUG] Page 72 → 100 hits

[DEBUG] Page 73 → 100 hits

[DEBUG] Page 74 → 100 hits

[DEBUG] Page 75 → 100 hits

[DEBUG] Page 76 → 100 hits

[DEBUG] Page 77 → 100 hits

[DEBUG] Page 78 → 100 hits

[DEBUG] Page 79 → 100 hits

[DEBUG] Page 80 → 100 hits

[DEBUG] Page 81 → 100 hits

[DEBUG] Page 82 → 100 hits

[DEBUG] Page 83 → 100 hits

[DEBUG] Page 84 → 100 hits

[DEBUG] Page 85 → 100 hits

[DEBUG] Page 86 → 100 hits

[DEBUG] Page 87 → 100 hits

[DEBUG] Page 88 → 100 hits

Overall Progress:  53%|█████▎    | 18946/35448 [02:30<02:04, 132.42rec/s]

[DEBUG] Page 89 → 71 hits
Fetching chunk: 4,900 records (2026-05-19 to 2026-05-28)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

Overall Progress:  53%|█████▎    | 18946/35448 [02:50<02:04, 132.42rec/s]

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

Overall Progress:  67%|██████▋   | 23846/35448 [03:05<01:26, 133.98rec/s]

[DEBUG] Page 49 → 100 hits
Fetching chunk: 6,665 records (2026-05-28 to 2026-06-06)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

Overall Progress:  67%|██████▋   | 23846/35448 [03:20<01:26, 133.98rec/s]

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

[DEBUG] Page 55 → 100 hits

[DEBUG] Page 56 → 100 hits

[DEBUG] Page 57 → 100 hits

[DEBUG] Page 58 → 100 hits

[DEBUG] Page 59 → 100 hits

[DEBUG] Page 60 → 100 hits

[DEBUG] Page 61 → 100 hits

[DEBUG] Page 62 → 100 hits

[DEBUG] Page 63 → 100 hits

[DEBUG] Page 64 → 100 hits

[DEBUG] Page 65 → 100 hits

[DEBUG] Page 66 → 100 hits

Overall Progress:  86%|████████▌ | 30511/35448 [03:51<00:35, 137.86rec/s]

[DEBUG] Page 67 → 65 hits
Fetching chunk: 4,936 records (2026-06-06 to 2026-06-14)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

Overall Progress:  86%|████████▌ | 30511/35448 [04:10<00:35, 137.86rec/s]

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

Overall Progress: 100%|█████████▉| 35447/35448 [04:27<00:00, 137.78rec/s]

[DEBUG] Page 50 → 36 hits

Overall Progress: 100%|█████████▉| 35447/35448 [04:28<00:00, 132.25rec/s]

Concatenating all chunks...
Fetch complete: 35,447 records retrieved (expected ~35,448)
Successfully retrieved 35447 records.
Unique records: N/A
Retrieved 35447 initial project records.
Initial programme distribution: {'unknown': 35447}
Applying comprehensive flattening to enriched records...
Creating final processed DataFrame...
Comprehensive processing complete! Final dataset: 35447 records, 43 columns
Total records: 35447
File size: 266.4 MB
[SUCCESS] data saved to /Users/kimwilmink/Desktop/ADS UU/Thesis ADS/Discourse_Analysis_EU_Budget_Strategy/data/project_data_31045243_20260806_183246.csv

In [4]:
h2020_data.head(10)

,metadata_es_SortDate,metadata_endDate,metadata_language,metadata_title,metadata_objective,metadata_callIdentifier,metadata_freeKeywords,metadata_DATASOURCE,metadata_REFERENCE,metadata_topicAbbreviation,...,databaseLabel,database,summary,weight,content,accessRestriction,enrichedMetadata,children,highlightedFragments,citation
0,2025-10-30T22:04:29.119+0100,2026-12-31T00:00:00.000+0100,en,A microbial perspective of major historical ev...,Microbes have played fundamental roles through...,ERC-2020-STG,"[The Americas, Ancient DNA, Native American po...",SEDIA_NONH2020_PROD,31045243948800,ERC-2020-STG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,A microbial perspective of major historical ev...,0.0,A microbial perspective of major historical ev...,False,NaN,NaN,NaN,A microbial perspective of major historical ev...
1,2025-10-30T02:03:33.117+0100,2025-02-28T00:00:00.000+0100,en,Embedded Electronic solutions for Polymer Inno...,El-Peacetolero’s overarching ambition is to de...,NFRP-2019-2020,"[Embedded optoelectronic system, Diagnosis of ...",SEDIA_NONH2020_PROD,31045243945320,NFRP-2019-2020-04,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Embedded Electronic solutions for Polymer Inno...,0.0,Embedded Electronic solutions for Polymer Inno...,False,NaN,NaN,NaN,Embedded Electronic solutions for Polymer Inno...
2,2025-10-29T21:56:18.755+0100,2025-12-31T00:00:00.000+0100,en,"Accurate, Reliable and Optimized functional MA...",The AROMA project will provide the means enabl...,H2020-FETOPEN-2018-2020,"[Ultra-high field, methods, RF pulse design, R...",SEDIA_NONH2020_PROD,31045243885876,FETOPEN-01-2018-2019-2020,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,"Accurate, Reliable and Optimized functional MA...",0.0,"Accurate, Reliable and Optimized functional MA...",False,NaN,NaN,NaN,"Accurate, Reliable and Optimized functional MA..."
3,2025-10-29T02:27:11.382+0100,2027-06-30T00:00:00.000+0100,en,Tracing language and population mixing in the ...,Chinese history was co-constructed by Han (Chi...,ERC-2019-ADG,"[populations, anthropolgoy, language contact]",SEDIA_NONH2020_PROD,31045243883700,ERC-2019-ADG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Tracing language and population mixing in the ...,0.0,Tracing language and population mixing in the ...,False,NaN,NaN,NaN,Tracing language and population mixing in the ...
4,2025-10-29T02:27:10.392+0100,2026-06-30T00:00:00.000+0100,en,Early Arabic Printing for the Arab Christians....,The main objective of the Project is to examin...,ERC-2019-ADG,"[Printing, Arab Christians, Arabic language, A...",SEDIA_NONH2020_PROD,31045243883219,ERC-2019-ADG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Early Arabic Printing for the Arab Christians....,0.0,Early Arabic Printing for the Arab Christians....,False,NaN,NaN,NaN,Early Arabic Printing for the Arab Christians....
5,2025-10-29T02:27:06.718+0100,2024-06-30T00:00:00.000+0100,en,Integrated Urban Electric Mobility Solutions i...,The project SOLUTIONSplus aims to set up a glo...,H2020-LC-GV-2018-2019-2020,"[Innovation, demonstration, e-mobility, intern...",SEDIA_NONH2020_PROD,31045243875041,LC-GV-05-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Integrated Urban Electric Mobility Solutions i...,0.0,Integrated Urban Electric Mobility Solutions i...,False,NaN,NaN,NaN,Integrated Urban Electric Mobility Solutions i...
6,2025-10-28T23:11:01.954+0100,2025-06-30T00:00:00.000+0100,en,Dynamic longitudinal exposome trajectories in ...,"Environmental factors, including air and noise...",H2020-SC1-BHC-2018-2020,"[Life-course, Cardiometabolic health trajector...",SEDIA_NONH2020_PROD,31045243874739,SC1-BHC-28-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Dynamic longitudinal exposome trajectories in ...,0.0,Dynamic longitudinal exposome trajectories in ...,False,NaN,NaN,NaN,Dynamic longitudinal exposome trajectories in ...
7,2025-10-28T03:03:15.150+0100,2024-12-31T00:00:00.000+0100,en,International Network for Terrestrial Research...,Planet Earth faces unprecedented environmental...,H2020-INFRAIA-2018-2020,"[Integrated, advanced pan-arctic infrastructur...",SEDIA_NONH2020_PROD,31045243871120,INFRAIA-01-2018-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,International Network for Terrestrial Research...,0.0,International Network for Terrestrial Research...,False,NaN,NaN,NaN,International Network for Terrestrial Research...
8,2025-10-28T03:03:01.311+0100,2024-11-30T00:00:00.000+0100,en,The Integrated Initiative of European Laser Re...,LASERLAB-EUROPE is the European consortium of ...,H2020-INFRAIA-2018-2020,"[Lasers, Physical Sciences, Optical Technologi...",SEDIA_NONH2020_PROD,31045243871124,INFRAIA-01-2018-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,The Integrated Initiative of European Laser Re...,0.0,The Integrated Initiative of European Laser Re...,False,NaN,NaN,NaN,The Integrated Initiative of European Laser Re...
9,2025-10-28T03:02:59.812+0100,2025-04-30T00:00:00.000+0100,en,European network for developing new horizons f...,This EURIZON project proposal is about Europea...,H2020-INFRASUPP-2018-2020,"[Research Infrastructures, European-Russian c...",SEDIA_NONH2020_PROD,31045243871072,INFRASUPP-01-2018-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,European network for developing new horizons f...,0.0,European network for developing new horizons f...,False,NaN,NaN,NaN,European network for developing new horizons f...

In [5]:
h2020_data.shape

(35447, 43)

In [6]:
h2020_data.columns

Index(['metadata_es_SortDate', 'metadata_endDate', 'metadata_language',
       'metadata_title', 'metadata_objective', 'metadata_callIdentifier',
       'metadata_freeKeywords', 'metadata_DATASOURCE', 'metadata_REFERENCE',
       'metadata_topicAbbreviation', 'metadata_overallBudget',
       'metadata_participants', 'metadata_es_ContentType', 'metadata_acronym',
       'metadata_programmes', 'metadata_legalEntityNames',
       'metadata_countries', 'metadata_euContributionRate', 'metadata_url',
       'metadata_esST_URL', 'metadata_euContributionAmount',
       'metadata_ecSignatureDate', 'metadata_nutsCode',
       'metadata_programAbbreviation', 'metadata_projectId',
       'metadata_programId', 'metadata_startDate', 'metadata_status',
       'apiVersion', 'reference', 'url', 'contentType', 'language',
       'databaseLabel', 'database', 'summary', 'weight', 'content',
       'accessRestriction', 'enrichedMetadata', 'children',
       'highlightedFragments', 'citation'],
      dtype='str')

In [19]:
for column in h2020_data:
    print(f"{column}: {h2020_data[column].isnull().sum()} - out of 35447 are NaN. This amounts to {h2020_data[column].isnull().sum() / 35447 * 100}%")

metadata_es_SortDate: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_endDate: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_language: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_title: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_objective: 3 - out of 35447 are NaN. This amounts to 0.008463339633819506%
metadata_callIdentifier: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_freeKeywords: 1884 - out of 35447 are NaN. This amounts to 5.314977290038649%
metadata_DATASOURCE: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_REFERENCE: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_topicAbbreviation: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_overallBudget: 36 - out of 35447 are NaN. This amounts to 0.10156007560583406%
metadata_participants: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_es_ContentType: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_acronym: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_programmes: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_legalEntityNames: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_countries: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_euContributionRate: 592 - out of 35447 are NaN. This amounts to 1.6700990210737157%
metadata_url: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_esST_URL: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_euContributionAmount: 36 - out of 35447 are NaN. This amounts to 0.10156007560583406%
metadata_ecSignatureDate: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_nutsCode: 5162 - out of 35447 are NaN. This amounts to 14.562586396592096%
metadata_programAbbreviation: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_projectId: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_programId: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_startDate: 0 - out of 35447 are NaN. This amounts to 0.0%
metadata_status: 0 - out of 35447 are NaN. This amounts to 0.0%
apiVersion: 0 - out of 35447 are NaN. This amounts to 0.0%
reference: 0 - out of 35447 are NaN. This amounts to 0.0%
url: 0 - out of 35447 are NaN. This amounts to 0.0%
contentType: 0 - out of 35447 are NaN. This amounts to 0.0%
language: 0 - out of 35447 are NaN. This amounts to 0.0%
databaseLabel: 0 - out of 35447 are NaN. This amounts to 0.0%
database: 0 - out of 35447 are NaN. This amounts to 0.0%
summary: 4 - out of 35447 are NaN. This amounts to 0.011284452845092673%
weight: 0 - out of 35447 are NaN. This amounts to 0.0%
content: 4 - out of 35447 are NaN. This amounts to 0.011284452845092673%
accessRestriction: 0 - out of 35447 are NaN. This amounts to 0.0%
enrichedMetadata: 35447 - out of 35447 are NaN. This amounts to 100.0%
children: 35447 - out of 35447 are NaN. This amounts to 100.0%
highlightedFragments: 35447 - out of 35447 are NaN. This amounts to 100.0%
citation: 0 - out of 35447 are NaN. This amounts to 0.0%

In [20]:
horizon_europe_data = fetcher.get('horizon', save=True)

Starting comprehensive fetch and processing for programme IDs: [43108390]...
🔍 DEBUG: Programme IDs being processed: [43108390]
🔍 DEBUG: Number of programmes: 1
Starting fetch for programme IDs: [43108390]...
Starting fetch with partitioning support...
Found 23,333 total records
Dataset exceeds 10,000 limit. Using date range partitioning...
Date range: 2025-05-01T01:31:01.868+0200 to 2026-08-06T18:27:54.391+0200

Overall Progress:   0%|          | 0/23333 [00:00<?, ?rec/s]

Splitting large chunk: 23,332 records (2025-05-01 to 2026-08-06)
Fetching chunk: 77 records (2025-05-01 to 2025-12-18)

Overall Progress:   0%|          | 77/23333 [00:01<09:32, 40.62rec/s]

[DEBUG] Page 1 → 77 hits
Splitting large chunk: 23,255 records (2025-12-18 to 2026-08-06)
Fetching chunk: 9 records (2025-12-18 to 2026-04-13)

Overall Progress:   0%|          | 86/23333 [00:04<25:59, 14.91rec/s]

[DEBUG] Page 1 → 9 hits
Splitting large chunk: 23,246 records (2026-04-13 to 2026-08-06)
Splitting large chunk: 19,700 records (2026-04-13 to 2026-06-09)
Fetching chunk: 3,546 records (2026-06-09 to 2026-08-06)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

Overall Progress:   0%|          | 86/23333 [00:23<25:59, 14.91rec/s]

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

Overall Progress:  16%|█▌        | 3632/23333 [00:32<02:45, 118.99rec/s]

[DEBUG] Page 36 → 46 hits
Splitting large chunk: 19,019 records (2026-04-13 to 2026-05-12)
Fetching chunk: 681 records (2026-05-12 to 2026-06-09)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

Overall Progress:  18%|█▊        | 4313/23333 [00:39<02:50, 111.50rec/s]

[DEBUG] Page 7 → 81 hits
Fetching chunk: 1,726 records (2026-04-13 to 2026-04-27)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

Overall Progress:  26%|██▌       | 6039/23333 [00:51<02:19, 124.31rec/s]

[DEBUG] Page 18 → 26 hits
Splitting large chunk: 17,293 records (2026-04-27 to 2026-05-12)
Fetching chunk: 3,386 records (2026-04-27 to 2026-05-04)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

Overall Progress:  26%|██▌       | 6039/23333 [01:03<02:19, 124.31rec/s]

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

Overall Progress:  40%|████      | 9425/23333 [01:19<01:54, 121.93rec/s]

[DEBUG] Page 34 → 86 hits
Splitting large chunk: 13,907 records (2026-05-04 to 2026-05-12)
Fetching chunk: 5,389 records (2026-05-04 to 2026-05-08)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

Overall Progress:  40%|████      | 9425/23333 [01:33<01:54, 121.93rec/s]

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

Overall Progress:  63%|██████▎   | 14814/23333 [02:01<01:07, 125.54rec/s]

[DEBUG] Page 54 → 89 hits
Fetching chunk: 8,518 records (2026-05-08 to 2026-05-12)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

Overall Progress:  63%|██████▎   | 14814/23333 [02:13<01:07, 125.54rec/s]

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

[DEBUG] Page 55 → 100 hits

[DEBUG] Page 56 → 100 hits

[DEBUG] Page 57 → 100 hits

[DEBUG] Page 58 → 100 hits

[DEBUG] Page 59 → 100 hits

[DEBUG] Page 60 → 100 hits

[DEBUG] Page 61 → 100 hits

[DEBUG] Page 62 → 100 hits

[DEBUG] Page 63 → 100 hits

[DEBUG] Page 64 → 100 hits

[DEBUG] Page 65 → 100 hits

[DEBUG] Page 66 → 100 hits

[DEBUG] Page 67 → 100 hits

[DEBUG] Page 68 → 100 hits

[DEBUG] Page 69 → 100 hits

[DEBUG] Page 70 → 100 hits

[DEBUG] Page 71 → 100 hits

[DEBUG] Page 72 → 100 hits

[DEBUG] Page 73 → 100 hits

[DEBUG] Page 74 → 100 hits

[DEBUG] Page 75 → 100 hits

[DEBUG] Page 76 → 100 hits

[DEBUG] Page 77 → 100 hits

[DEBUG] Page 78 → 100 hits

[DEBUG] Page 79 → 100 hits

[DEBUG] Page 80 → 100 hits

[DEBUG] Page 81 → 100 hits

[DEBUG] Page 82 → 100 hits

[DEBUG] Page 83 → 100 hits

[DEBUG] Page 84 → 100 hits

[DEBUG] Page 85 → 100 hits

Overall Progress: 100%|█████████▉| 23332/23333 [03:07<00:00, 127.04rec/s]

[DEBUG] Page 86 → 18 hits

Overall Progress: 100%|█████████▉| 23332/23333 [03:08<00:00, 123.83rec/s]

Concatenating all chunks...
Fetch complete: 23,332 records retrieved (expected ~23,333)
Successfully retrieved 23332 records.
Unique records: N/A
Retrieved 23332 initial project records.
Initial programme distribution: {'unknown': 23332}
Applying comprehensive flattening to enriched records...
Creating final processed DataFrame...
Comprehensive processing complete! Final dataset: 23332 records, 43 columns
Total records: 23332
File size: 199.4 MB
[SUCCESS] data saved to /Users/kimwilmink/Desktop/ADS UU/Thesis ADS/Discourse_Analysis_EU_Budget_Strategy/data/project_data_43108390_20260806_184045.csv

In [21]:
horizon_europe_data.head(10)

,metadata_es_SortDate,metadata_endDate,metadata_language,metadata_title,metadata_objective,metadata_callIdentifier,metadata_freeKeywords,metadata_DATASOURCE,metadata_REFERENCE,metadata_topicAbbreviation,...,databaseLabel,database,summary,weight,content,accessRestriction,enrichedMetadata,children,highlightedFragments,citation
0,2025-12-17T23:23:16.707+0100,2027-05-31T00:00:00.000+0100,en,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...,SUNBIO brings together a significant variety o...,HORIZON-MISS-2023-OCEAN-01,"[wave energy, solar energy, thermal energy, ma...",SEDIA_NONH2020_PROD,43108390101157493,HORIZON-MISS-2023-OCEAN-01-06,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...,0.0,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...,False,NaN,NaN,NaN,SUSTAINABLE AND NATURE INCLUSIVE OFFSHORE ENER...
1,2025-12-16T14:48:37.868+0100,2028-12-31T00:00:00.000+0100,en,Three Dimensional Quantum Nanomaterials,Quantum nanomaterials are highly relevant for ...,ERC-2023-STG,None,SEDIA_NONH2020_PROD,43108390101116043,ERC-2023-STG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Three Dimensional Quantum Nanomaterials,0.0,Three Dimensional Quantum Nanomaterials,False,NaN,NaN,NaN,Three Dimensional Quantum Nanomaterials. Avail...
2,2025-12-16T14:12:26.033+0100,2028-09-30T00:00:00.000+0100,en,How to evolve without centromeres: meiotic rec...,Centromeres strongly affect genomic architectu...,ERC-2023-STG,"[centromere, holocentric chromosome, chromosom...",SEDIA_NONH2020_PROD,43108390101114879,ERC-2023-STG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,How to evolve without centromeres: meiotic rec...,0.0,How to evolve without centromeres: meiotic rec...,False,NaN,NaN,NaN,How to evolve without centromeres: meiotic rec...
3,2025-12-15T17:27:52.798+0100,2026-07-31T00:00:00.000+0100,en,Geography and Cartography in Dante's «Comedy»,\nThe GEODETIC project aims to explore an unde...,HORIZON-MSCA-2022-PF-01,"[Dante Studies, Medieval and Italian Studies, ...",SEDIA_NONH2020_PROD,43108390101110048,HORIZON-MSCA-2022-PF-01-01,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Geography and Cartography in Dante's «Comedy»,0.0,Geography and Cartography in Dante's «Comedy»,False,NaN,NaN,NaN,Geography and Cartography in Dante's «Comedy»....
4,2025-12-15T17:19:18.372+0100,2025-09-30T00:00:00.000+0100,en,Investigating if recuperating hepatic macropha...,Liver fibrosis is the build-up of scar tissue ...,HORIZON-MSCA-2022-PF-01,Macrophages; Fibrosis; Cirrhosis; Infection; M...,SEDIA_NONH2020_PROD,43108390101109513,HORIZON-MSCA-2022-PF-01-01,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Investigating if recuperating hepatic macropha...,0.0,Investigating if recuperating hepatic macropha...,False,NaN,NaN,NaN,Investigating if recuperating hepatic macropha...
5,2025-12-15T05:22:58.915+0100,2025-12-31T00:00:00.000+0100,en,Automated zero-touch cross-layer provisioning ...,NaN,HORIZON-JU-SNS-2022,"[5G, 6G, service orchestration, zero-touch pro...",SEDIA_NONH2020_PROD,43108390101097122,HORIZON-JU-SNS-2022-STREAM-A-01-07,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Automated zero-touch cross-layer provisioning ...,0.0,Automated zero-touch cross-layer provisioning ...,False,NaN,NaN,NaN,Automated zero-touch cross-layer provisioning ...
6,2025-12-15T05:22:50.224+0100,2026-12-31T00:00:00.000+0100,en,A European “shield” against colorectal cancer ...,With Colorectal Cancer (CRC) being accountable...,HORIZON-MISS-2021-CANCER-02,"[Colorectal cancer screening, early detection,...",SEDIA_NONH2020_PROD,43108390101097036,HORIZON-MISS-2021-CANCER-02-01,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,A European “shield” against colorectal cancer ...,0.0,A European “shield” against colorectal cancer ...,False,NaN,NaN,NaN,A European “shield” against colorectal cancer ...
7,2025-12-15T01:00:34.786+0100,2027-01-31T00:00:00.000+0100,en,Modular AXIal flux Motor for Automotive,The massive electrification of automotive vehi...,HORIZON-CL5-2022-D5-01,"[electrical machine, mass production, manufact...",SEDIA_NONH2020_PROD,43108390101096097,HORIZON-CL5-2022-D5-01-09,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Modular AXIal flux Motor for Automotive,0.0,Modular AXIal flux Motor for Automotive,False,NaN,NaN,NaN,Modular AXIal flux Motor for Automotive. Avail...
8,2025-12-14T23:34:25.721+0100,2026-12-31T00:00:00.000+0100,en,Systemic Endotoxemia as the driver of chronic ...,Rheumatic diseases (RDs) affect more than 40% ...,HORIZON-HLTH-2022-STAYHLTH-02,"[chronic inflammation, Microbiota, systemic en...",SEDIA_NONH2020_PROD,43108390101095084,HORIZON-HLTH-2022-STAYHLTH-02-01,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Systemic Endotoxemia as the driver of chronic ...,0.0,Systemic Endotoxemia as the driver of chronic ...,False,NaN,NaN,NaN,Systemic Endotoxemia as the driver of chronic ...
9,2025-12-14T22:07:27.753+0100,2028-12-31T00:00:00.000+0100,en,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,Chronic inflammation underlies several disease...,HORIZON-HLTH-2022-STAYHLTH-02,Glycosylation; Microbiome; Innate Immune Respo...,SEDIA_NONH2020_PROD,43108390101093997,HORIZON-HLTH-2022-STAYHLTH-02-01,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,0.0,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,False,NaN,NaN,NaN,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...

In [22]:
horizon_europe_data.shape

(23332, 43)

In [23]:
horizon_europe_data.columns

Index(['metadata_es_SortDate', 'metadata_endDate', 'metadata_language',
       'metadata_title', 'metadata_objective', 'metadata_callIdentifier',
       'metadata_freeKeywords', 'metadata_DATASOURCE', 'metadata_REFERENCE',
       'metadata_topicAbbreviation', 'metadata_overallBudget',
       'metadata_participants', 'metadata_es_ContentType', 'metadata_acronym',
       'metadata_programmes', 'metadata_legalEntityNames',
       'metadata_countries', 'metadata_euContributionRate', 'metadata_url',
       'metadata_esST_URL', 'metadata_euContributionAmount',
       'metadata_ecSignatureDate', 'metadata_nutsCode',
       'metadata_programAbbreviation', 'metadata_projectId',
       'metadata_programId', 'metadata_startDate', 'metadata_status',
       'apiVersion', 'reference', 'url', 'contentType', 'language',
       'databaseLabel', 'database', 'summary', 'weight', 'content',
       'accessRestriction', 'enrichedMetadata', 'children',
       'highlightedFragments', 'citation'],
      dtype='str')

In [25]:
for column in horizon_europe_data.columns:
    print(f"{column}: {horizon_europe_data[column].isnull().sum()} - out of 23332 are NaN. This amounts to {horizon_europe_data[column].isnull().sum() / 23332 * 100}%")

metadata_es_SortDate: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_endDate: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_language: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_title: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_objective: 12 - out of 23332 are NaN. This amounts to 0.051431510372021254%
metadata_callIdentifier: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_freeKeywords: 2092 - out of 23332 are NaN. This amounts to 8.966226641522372%
metadata_DATASOURCE: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_REFERENCE: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_topicAbbreviation: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_overallBudget: 16 - out of 23332 are NaN. This amounts to 0.06857534716269502%
metadata_participants: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_es_ContentType: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_acronym: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_programmes: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_legalEntityNames: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_countries: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_euContributionRate: 12482 - out of 23332 are NaN. This amounts to 53.49734270529745%
metadata_url: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_esST_URL: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_euContributionAmount: 16 - out of 23332 are NaN. This amounts to 0.06857534716269502%
metadata_ecSignatureDate: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_nutsCode: 1447 - out of 23332 are NaN. This amounts to 6.20178295902623%
metadata_programAbbreviation: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_projectId: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_programId: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_startDate: 0 - out of 23332 are NaN. This amounts to 0.0%
metadata_status: 0 - out of 23332 are NaN. This amounts to 0.0%
apiVersion: 0 - out of 23332 are NaN. This amounts to 0.0%
reference: 0 - out of 23332 are NaN. This amounts to 0.0%
url: 0 - out of 23332 are NaN. This amounts to 0.0%
contentType: 0 - out of 23332 are NaN. This amounts to 0.0%
language: 0 - out of 23332 are NaN. This amounts to 0.0%
databaseLabel: 0 - out of 23332 are NaN. This amounts to 0.0%
database: 0 - out of 23332 are NaN. This amounts to 0.0%
summary: 3 - out of 23332 are NaN. This amounts to 0.012857877593005313%
weight: 0 - out of 23332 are NaN. This amounts to 0.0%
content: 3 - out of 23332 are NaN. This amounts to 0.012857877593005313%
accessRestriction: 0 - out of 23332 are NaN. This amounts to 0.0%
enrichedMetadata: 23332 - out of 23332 are NaN. This amounts to 100.0%
children: 23332 - out of 23332 are NaN. This amounts to 100.0%
highlightedFragments: 23332 - out of 23332 are NaN. This amounts to 100.0%
citation: 0 - out of 23332 are NaN. This amounts to 0.0%

In [26]:
combined_data = fetcher.get(['h2020', 'horizon'], save=True)

Starting comprehensive fetch and processing for programme IDs: [31045243, 43108390]...
🔍 DEBUG: Programme IDs being processed: [31045243, 43108390]
🔍 DEBUG: Number of programmes: 2
Starting fetch for programme IDs: [31045243, 43108390]...
Starting fetch with partitioning support...
Found 58,781 total records
Dataset exceeds 10,000 limit. Using date range partitioning...
Date range: 2025-01-24T14:32:52.086+0100 to 2026-08-06T18:27:54.391+0200

Overall Progress:   0%|          | 0/58781 [00:00<?, ?rec/s]

Splitting large chunk: 58,780 records (2025-01-24 to 2026-08-06)
Fetching chunk: 467 records (2025-01-24 to 2025-10-31)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

Overall Progress:   1%|          | 467/58781 [00:05<11:59, 81.00rec/s]

[DEBUG] Page 5 → 67 hits
Splitting large chunk: 58,313 records (2025-10-31 to 2026-08-06)
Fetching chunk: 89 records (2025-10-31 to 2026-03-19)

Overall Progress:   1%|          | 556/58781 [00:07<13:56, 69.61rec/s]

[DEBUG] Page 1 → 89 hits
Splitting large chunk: 58,224 records (2026-03-19 to 2026-08-06)
Splitting large chunk: 36,625 records (2026-03-19 to 2026-05-28)
Splitting large chunk: 21,599 records (2026-05-28 to 2026-08-06)
Fetching chunk: 2,429 records (2026-03-19 to 2026-04-23)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

Overall Progress:   1%|          | 556/58781 [00:24<13:56, 69.61rec/s]

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

Overall Progress:   5%|▌         | 2985/58781 [00:28<08:25, 110.46rec/s]

[DEBUG] Page 25 → 29 hits
Splitting large chunk: 34,196 records (2026-04-23 to 2026-05-28)
Splitting large chunk: 17,226 records (2026-05-28 to 2026-07-02)
Fetching chunk: 4,373 records (2026-07-02 to 2026-08-06)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

Overall Progress:   5%|▌         | 2985/58781 [00:45<08:25, 110.46rec/s]

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

Overall Progress:  13%|█▎        | 7358/58781 [01:08<07:53, 108.62rec/s]

[DEBUG] Page 44 → 73 hits
Splitting large chunk: 19,766 records (2026-04-23 to 2026-05-11)
Splitting large chunk: 14,430 records (2026-05-11 to 2026-05-28)
Splitting large chunk: 11,688 records (2026-05-28 to 2026-06-15)
Fetching chunk: 5,538 records (2026-06-15 to 2026-07-02)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

Overall Progress:  13%|█▎        | 7358/58781 [01:25<07:53, 108.62rec/s]

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

[DEBUG] Page 55 → 100 hits

Overall Progress:  22%|██▏       | 12896/58781 [01:53<06:34, 116.21rec/s]

[DEBUG] Page 56 → 38 hits
Fetching chunk: 3,381 records (2026-04-23 to 2026-05-02)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

Overall Progress:  22%|██▏       | 12896/58781 [02:05<06:34, 116.21rec/s]

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

Overall Progress:  28%|██▊       | 16277/58781 [02:18<05:46, 122.61rec/s]

[DEBUG] Page 34 → 81 hits
Splitting large chunk: 16,385 records (2026-05-02 to 2026-05-11)
Fetching chunk: 9,527 records (2026-05-11 to 2026-05-20)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

Overall Progress:  28%|██▊       | 16277/58781 [02:35<05:46, 122.61rec/s]

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

[DEBUG] Page 55 → 100 hits

[DEBUG] Page 56 → 100 hits

[DEBUG] Page 57 → 100 hits

[DEBUG] Page 58 → 100 hits

[DEBUG] Page 59 → 100 hits

[DEBUG] Page 60 → 100 hits

[DEBUG] Page 61 → 100 hits

[DEBUG] Page 62 → 100 hits

[DEBUG] Page 63 → 100 hits

[DEBUG] Page 64 → 100 hits

[DEBUG] Page 65 → 100 hits

[DEBUG] Page 66 → 100 hits

[DEBUG] Page 67 → 100 hits

[DEBUG] Page 68 → 100 hits

[DEBUG] Page 69 → 100 hits

[DEBUG] Page 70 → 100 hits

[DEBUG] Page 71 → 100 hits

[DEBUG] Page 72 → 100 hits

[DEBUG] Page 73 → 100 hits

[DEBUG] Page 74 → 100 hits

[DEBUG] Page 75 → 100 hits

[DEBUG] Page 76 → 100 hits

[DEBUG] Page 77 → 100 hits

[DEBUG] Page 78 → 100 hits

[DEBUG] Page 79 → 100 hits

[DEBUG] Page 80 → 100 hits

[DEBUG] Page 81 → 100 hits

[DEBUG] Page 82 → 100 hits

[DEBUG] Page 83 → 100 hits

[DEBUG] Page 84 → 100 hits

[DEBUG] Page 85 → 100 hits

[DEBUG] Page 86 → 100 hits

[DEBUG] Page 87 → 100 hits

[DEBUG] Page 88 → 100 hits

[DEBUG] Page 89 → 100 hits

[DEBUG] Page 90 → 100 hits

[DEBUG] Page 91 → 100 hits

[DEBUG] Page 92 → 100 hits

[DEBUG] Page 93 → 100 hits

[DEBUG] Page 94 → 100 hits

[DEBUG] Page 95 → 100 hits

Overall Progress:  44%|████▍     | 25804/58781 [03:27<04:13, 130.33rec/s]

[DEBUG] Page 96 → 27 hits
Fetching chunk: 4,903 records (2026-05-20 to 2026-05-28)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

Overall Progress:  44%|████▍     | 25804/58781 [03:45<04:13, 130.33rec/s]

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

Overall Progress:  52%|█████▏    | 30707/58781 [04:09<03:42, 126.08rec/s]

[DEBUG] Page 50 → 3 hits
Fetching chunk: 6,872 records (2026-05-28 to 2026-06-06)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

Overall Progress:  52%|█████▏    | 30707/58781 [04:25<03:42, 126.08rec/s]

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

[DEBUG] Page 55 → 100 hits

[DEBUG] Page 56 → 100 hits

[DEBUG] Page 57 → 100 hits

[DEBUG] Page 58 → 100 hits

[DEBUG] Page 59 → 100 hits

[DEBUG] Page 60 → 100 hits

[DEBUG] Page 61 → 100 hits

[DEBUG] Page 62 → 100 hits

[DEBUG] Page 63 → 100 hits

[DEBUG] Page 64 → 100 hits

[DEBUG] Page 65 → 100 hits

[DEBUG] Page 66 → 100 hits

[DEBUG] Page 67 → 100 hits

[DEBUG] Page 68 → 100 hits

Overall Progress:  64%|██████▍   | 37579/58781 [04:57<02:40, 131.77rec/s]

[DEBUG] Page 69 → 72 hits
Fetching chunk: 4,816 records (2026-06-06 to 2026-06-15)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

Overall Progress:  64%|██████▍   | 37579/58781 [05:15<02:40, 131.77rec/s]

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

Overall Progress:  72%|███████▏  | 42395/58781 [05:31<02:01, 134.40rec/s]

[DEBUG] Page 49 → 16 hits
Fetching chunk: 4,664 records (2026-05-02 to 2026-05-07)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

Overall Progress:  72%|███████▏  | 42395/58781 [05:45<02:01, 134.40rec/s]

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

Overall Progress:  80%|████████  | 47059/58781 [06:05<01:26, 135.14rec/s]

[DEBUG] Page 47 → 64 hits
Splitting large chunk: 11,721 records (2026-05-07 to 2026-05-11)
Fetching chunk: 4,313 records (2026-05-07 to 2026-05-09)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

Overall Progress:  80%|████████  | 47059/58781 [06:25<01:26, 135.14rec/s]

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

Overall Progress:  87%|████████▋ | 51372/58781 [06:41<00:56, 131.23rec/s]

[DEBUG] Page 44 → 13 hits
Fetching chunk: 7,408 records (2026-05-09 to 2026-05-11)

[DEBUG] Page 1 → 100 hits

[DEBUG] Page 2 → 100 hits

[DEBUG] Page 3 → 100 hits

[DEBUG] Page 4 → 100 hits

[DEBUG] Page 5 → 100 hits

[DEBUG] Page 6 → 100 hits

[DEBUG] Page 7 → 100 hits

[DEBUG] Page 8 → 100 hits

[DEBUG] Page 9 → 100 hits

[DEBUG] Page 10 → 100 hits

[DEBUG] Page 11 → 100 hits

[DEBUG] Page 12 → 100 hits

[DEBUG] Page 13 → 100 hits

[DEBUG] Page 14 → 100 hits

[DEBUG] Page 15 → 100 hits

[DEBUG] Page 16 → 100 hits

[DEBUG] Page 17 → 100 hits

[DEBUG] Page 18 → 100 hits

[DEBUG] Page 19 → 100 hits

Overall Progress:  87%|████████▋ | 51372/58781 [06:55<00:56, 131.23rec/s]

[DEBUG] Page 20 → 100 hits

[DEBUG] Page 21 → 100 hits

[DEBUG] Page 22 → 100 hits

[DEBUG] Page 23 → 100 hits

[DEBUG] Page 24 → 100 hits

[DEBUG] Page 25 → 100 hits

[DEBUG] Page 26 → 100 hits

[DEBUG] Page 27 → 100 hits

[DEBUG] Page 28 → 100 hits

[DEBUG] Page 29 → 100 hits

[DEBUG] Page 30 → 100 hits

[DEBUG] Page 31 → 100 hits

[DEBUG] Page 32 → 100 hits

[DEBUG] Page 33 → 100 hits

[DEBUG] Page 34 → 100 hits

[DEBUG] Page 35 → 100 hits

[DEBUG] Page 36 → 100 hits

[DEBUG] Page 37 → 100 hits

[DEBUG] Page 38 → 100 hits

[DEBUG] Page 39 → 100 hits

[DEBUG] Page 40 → 100 hits

[DEBUG] Page 41 → 100 hits

[DEBUG] Page 42 → 100 hits

[DEBUG] Page 43 → 100 hits

[DEBUG] Page 44 → 100 hits

[DEBUG] Page 45 → 100 hits

[DEBUG] Page 46 → 100 hits

[DEBUG] Page 47 → 100 hits

[DEBUG] Page 48 → 100 hits

[DEBUG] Page 49 → 100 hits

[DEBUG] Page 50 → 100 hits

[DEBUG] Page 51 → 100 hits

[DEBUG] Page 52 → 100 hits

[DEBUG] Page 53 → 100 hits

[DEBUG] Page 54 → 100 hits

[DEBUG] Page 55 → 100 hits

[DEBUG] Page 56 → 100 hits

[DEBUG] Page 57 → 100 hits

[DEBUG] Page 58 → 100 hits

[DEBUG] Page 59 → 100 hits

[DEBUG] Page 60 → 100 hits

[DEBUG] Page 61 → 100 hits

[DEBUG] Page 62 → 100 hits

[DEBUG] Page 63 → 100 hits

[DEBUG] Page 64 → 100 hits

[DEBUG] Page 65 → 100 hits

[DEBUG] Page 66 → 100 hits

[DEBUG] Page 67 → 100 hits

[DEBUG] Page 68 → 100 hits

[DEBUG] Page 69 → 100 hits

[DEBUG] Page 70 → 100 hits

[DEBUG] Page 71 → 100 hits

[DEBUG] Page 72 → 100 hits

[DEBUG] Page 73 → 100 hits

[DEBUG] Page 74 → 100 hits

Overall Progress: 100%|█████████▉| 58780/58781 [07:36<00:00, 131.99rec/s]

[DEBUG] Page 75 → 8 hits

Overall Progress: 100%|█████████▉| 58780/58781 [07:37<00:00, 128.54rec/s]

Concatenating all chunks...
Fetch complete: 58,780 records retrieved (expected ~58,781)
Successfully retrieved 58780 records.
Unique records: N/A
Retrieved 58780 initial project records.
Initial programme distribution: {'unknown': 58780}
Applying comprehensive flattening to enriched records...
Creating final processed DataFrame...
Comprehensive processing complete! Final dataset: 58780 records, 43 columns
Total records: 58780
File size: 465.8 MB
[SUCCESS] data saved to /Users/kimwilmink/Desktop/ADS UU/Thesis ADS/Discourse_Analysis_EU_Budget_Strategy/data/project_data_31045243_43108390_20260806_185039.csv

In [27]:
combined_data.head(10)

,metadata_es_SortDate,metadata_endDate,metadata_language,metadata_title,metadata_objective,metadata_callIdentifier,metadata_freeKeywords,metadata_DATASOURCE,metadata_REFERENCE,metadata_topicAbbreviation,...,databaseLabel,database,summary,weight,content,accessRestriction,enrichedMetadata,children,highlightedFragments,citation
0,2025-10-31T03:41:37.475+0100,2024-08-31T00:00:00.000+0100,en,Sustainable 5G deployment model for future mob...,5GMed brings together key stakeholders of the ...,H2020-ICT-2018-20,"[5G-enabled mobility, cross-border corridor, c...",SEDIA_NONH2020_PROD,31045243951947,ICT-53-2020,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Sustainable 5G deployment model for future mob...,0.0,Sustainable 5G deployment model for future mob...,False,NaN,NaN,NaN,Sustainable 5G deployment model for future mob...
1,2025-10-30T22:04:29.119+0100,2026-12-31T00:00:00.000+0100,en,A microbial perspective of major historical ev...,Microbes have played fundamental roles through...,ERC-2020-STG,"[The Americas, Ancient DNA, Native American po...",SEDIA_NONH2020_PROD,31045243948800,ERC-2020-STG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,A microbial perspective of major historical ev...,0.0,A microbial perspective of major historical ev...,False,NaN,NaN,NaN,A microbial perspective of major historical ev...
2,2025-10-30T02:03:33.117+0100,2025-02-28T00:00:00.000+0100,en,Embedded Electronic solutions for Polymer Inno...,El-Peacetolero’s overarching ambition is to de...,NFRP-2019-2020,"[Embedded optoelectronic system, Diagnosis of ...",SEDIA_NONH2020_PROD,31045243945320,NFRP-2019-2020-04,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Embedded Electronic solutions for Polymer Inno...,0.0,Embedded Electronic solutions for Polymer Inno...,False,NaN,NaN,NaN,Embedded Electronic solutions for Polymer Inno...
3,2025-10-29T21:56:18.755+0100,2025-12-31T00:00:00.000+0100,en,"Accurate, Reliable and Optimized functional MA...",The AROMA project will provide the means enabl...,H2020-FETOPEN-2018-2020,"[Ultra-high field, methods, RF pulse design, R...",SEDIA_NONH2020_PROD,31045243885876,FETOPEN-01-2018-2019-2020,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,"Accurate, Reliable and Optimized functional MA...",0.0,"Accurate, Reliable and Optimized functional MA...",False,NaN,NaN,NaN,"Accurate, Reliable and Optimized functional MA..."
4,2025-10-29T02:27:11.382+0100,2027-06-30T00:00:00.000+0100,en,Tracing language and population mixing in the ...,Chinese history was co-constructed by Han (Chi...,ERC-2019-ADG,"[populations, anthropolgoy, language contact]",SEDIA_NONH2020_PROD,31045243883700,ERC-2019-ADG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Tracing language and population mixing in the ...,0.0,Tracing language and population mixing in the ...,False,NaN,NaN,NaN,Tracing language and population mixing in the ...
5,2025-10-29T02:27:10.392+0100,2026-06-30T00:00:00.000+0100,en,Early Arabic Printing for the Arab Christians....,The main objective of the Project is to examin...,ERC-2019-ADG,"[Printing, Arab Christians, Arabic language, A...",SEDIA_NONH2020_PROD,31045243883219,ERC-2019-ADG,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Early Arabic Printing for the Arab Christians....,0.0,Early Arabic Printing for the Arab Christians....,False,NaN,NaN,NaN,Early Arabic Printing for the Arab Christians....
6,2025-10-29T02:27:06.718+0100,2024-06-30T00:00:00.000+0100,en,Integrated Urban Electric Mobility Solutions i...,The project SOLUTIONSplus aims to set up a glo...,H2020-LC-GV-2018-2019-2020,"[Innovation, demonstration, e-mobility, intern...",SEDIA_NONH2020_PROD,31045243875041,LC-GV-05-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Integrated Urban Electric Mobility Solutions i...,0.0,Integrated Urban Electric Mobility Solutions i...,False,NaN,NaN,NaN,Integrated Urban Electric Mobility Solutions i...
7,2025-10-28T23:11:01.954+0100,2025-06-30T00:00:00.000+0100,en,Dynamic longitudinal exposome trajectories in ...,"Environmental factors, including air and noise...",H2020-SC1-BHC-2018-2020,"[Life-course, Cardiometabolic health trajector...",SEDIA_NONH2020_PROD,31045243874739,SC1-BHC-28-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,Dynamic longitudinal exposome trajectories in ...,0.0,Dynamic longitudinal exposome trajectories in ...,False,NaN,NaN,NaN,Dynamic longitudinal exposome trajectories in ...
8,2025-10-28T03:03:15.150+0100,2024-12-31T00:00:00.000+0100,en,International Network for Terrestrial Research...,Planet Earth faces unprecedented environmental...,H2020-INFRAIA-2018-2020,"[Integrated, advanced pan-arctic infrastructur...",SEDIA_NONH2020_PROD,31045243871120,INFRAIA-01-2018-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,International Network for Terrestrial Research...,0.0,International Network for Terrestrial Research...,False,NaN,NaN,NaN,International Network for Terrestrial Research...
9,2025-10-28T03:03:01.311+0100,2024-11-30T00:00:00.000+0100,en,The Integrated Initiative of European Laser Re...,LASERLAB-EUROPE is the European consortium of ...,H2020-INFRAIA-2018-2020,"[Lasers, Physical Sciences, Optical Technologi...",SEDIA_NONH2020_PROD,31045243871124,INFRAIA-01-2018-2019,...,SEDIA_NONH2020_PROD,SEDIA_NONH2020_PROD,The Integrated Initiative of European Laser Re...,0.0,The Integrated Initiative of European Laser Re...,False,NaN,NaN,NaN,The Integrated Initiative of European Laser Re...

In [28]:
combined_data.shape

(58780, 43)

In [29]:
for column in combined_data.columns:
    print(f"{column}: {combined_data[column].isnull().sum()}")

metadata_es_SortDate: 0
metadata_endDate: 0
metadata_language: 0
metadata_title: 0
metadata_objective: 15
metadata_callIdentifier: 0
metadata_freeKeywords: 3976
metadata_DATASOURCE: 0
metadata_REFERENCE: 0
metadata_topicAbbreviation: 0
metadata_overallBudget: 52
metadata_participants: 0
metadata_es_ContentType: 0
metadata_acronym: 0
metadata_programmes: 0
metadata_legalEntityNames: 0
metadata_countries: 0
metadata_euContributionRate: 13074
metadata_url: 0
metadata_esST_URL: 0
metadata_euContributionAmount: 52
metadata_ecSignatureDate: 0
metadata_nutsCode: 6609
metadata_programAbbreviation: 0
metadata_projectId: 0
metadata_programId: 0
metadata_startDate: 0
metadata_status: 0
apiVersion: 0
reference: 0
url: 0
contentType: 0
language: 0
databaseLabel: 0
database: 0
summary: 7
weight: 0
content: 7
accessRestriction: 0
enrichedMetadata: 58780
children: 58780
highlightedFragments: 58780
citation: 0

In [31]:
datasets = [h2020_data, horizon_europe_data, combined_data]

In [39]:
h2020_data.to_csv(f"data/h2020_data.csv", index=False)
horizon_europe_data.to_csv(f"data/horizon_europe_data.csv", index=False)
combined_data.to_csv(f"data/combined_data.csv", index=False)